version: "3"
services:
  vscode_docker:
    build: .
    user: dev
    hostname: vsdocker
    volumes:
      # Volume code accessible
      - ./app:/app:rw
      # unix X11
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # vscode extension & params
      - /srv/vsdocker/extensions:/home/dev/.vscode:rw
      - /srv/vsdocker/code:/home/dev/.config/Code:rw
      # Accès aux clès SSH + know_hosts
      - ${HOME}/.ssh:/home/dev/.ssh:rw
      # Créditentials git
      - ${HOME}/.gitconfig:/home/dev/.gitconfig:ro
    environment:
      - DISPLAY=unix${DISPLAY}
    container_name: vsdocker
    command: "sleep infinity"
